# -*- coding: utf-8 -*-
"""ARIMA_BIKES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfX5fhx1sPWRaYiv8HDLa0Pm-gD1kR7z
"""

import pandas as pd
import matplotlib.pyplot as plt

folder_predict='/content/drive/MyDrive/CAP1/'
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

df=pd.read_excel(folder_predict+'Bikessales_RSL.xlsx')

df

df.drop(columns=['EnglishProductCategoryName'], inplace=True)

df['FullDateAlternateKey'] = df['FullDateAlternateKey'].dt.strftime('%Y-%m')

df

df.set_index('FullDateAlternateKey', inplace=True)

df = df.groupby('FullDateAlternateKey')['RS_Sales'].sum()

df.plot(figsize=(25, 6))

import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
!pip install pmdarima
import pmdarima as pm

def arimamodel(timeseries):
    automodel = pm.auto_arima(timeseries, start_p=1, start_q=1, max_p=5, max_q=5, test='adf', seasonal=False, trace=True)
    return automodel

arimamodel(df)

pd.options.display.float_format = '{:,.0f}'.format
from statsmodels.tsa.arima.model import ARIMA

pd.options.display.float_format = '{:,.0f}'.format

model = ARIMA(df, order=(3, 2, 1))
model_fit = model.fit()
forecast_result = model_fit.forecast(12)

df_forecast = forecast_result.reset_index()
df_forecast.columns = ['Date', 'Predicted_Sales']

print(df_forecast)

plt.figure(figsize=(20, 5))
plt.plot(df_forecast['Date'], df_forecast['Predicted_Sales'], marker='o', linestyle='-')
for i, sales in enumerate(df_forecast['Predicted_Sales']):
    plt.text(df_forecast['Date'][i], sales, f'{sales:,.0f}', ha='right', va='bottom')

df = df.to_frame()

df.reset_index(inplace=True)

df.head()

df_forecast

df_forecast.to_excel("df_forecast.xlsx", index=False)

df.to_excel("df.xlsx", index=False)

df_predict=pd.read_excel(folder_predict+'Final.xlsx')

df_predict

df_predict.info()

df_predict.plot(x='FullDateAlternateKey', y='RS_Sales', figsize=(30, 10))
for i, sales in enumerate(df_predict['RS_Sales']):
    plt.text(df_predict['FullDateAlternateKey'][i], sales, f'{sales:,.0f}', ha='right', va='bottom')